version: '3.9'

services:
  redis:
    image: "redis:7-alpine"
    container_name: valyxa-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  python_app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PROJECT_DIR: "${PROJECT_DIR}"
    container_name: valyxa-python
    image: valyxa-python:prod
    volumes:
      - ./:${PROJECT_DIR}
      - ./translations:${PROJECT_DIR}/translations
    depends_on:
      - redis
    environment:
      PROJECT_DIR: "${PROJECT_DIR}"
      REDIS_URL: "${REDIS_URL}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      LANGUAGES: "${LANGUAGES}"
    command: ["${PROJECT_DIR}/scripts/start.sh"]
