version: '3.9'

services:
  redis:
    image: "redis:6.2-alpine"
    container_name: valyxa-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  python_app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PROJECT_DIR: /srv/app
    container_name: valyxa-python
    volumes:
      - ./:/srv/app
    depends_on:
      - redis
    env_file:
      - .env
